### ISSUE TITLE
Make Destination part of the Options?

### ISSUE THREAD

**Issue by chrisspiegl** [wulkano/aperture-node#26] opened 2022-03-11 12:26 UTC
Would it be possible to make the destination part of the options object so that one could choose the file destination of the recording before?

I find this specifically interesting to put the recording of ProRes onto an external SSD.

https://github.com/wulkano/aperture-node/blob/75e0ec93a32fd99f8193235df1988058582da456/index.js#L78

**Comment by sindresorhus** [comment] 2022-03-11 16:05
Duplicate of #9

**Closed by sindresorhus** 2022-03-11 16:05 UTC
